---
name: CI
on:
  - pull_request
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
          - 20.x
          - 22.x
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Lint
        if: ${{ !env.ACT }} # Skip linting if we're running Act since we do that via Husky & lint-staged locally.
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Check spec types
        run: npm run check-spec-types
      - name: Check API
        run: npx api-extractor run
